### ISSUE TITLE
LoadError: UndefVarError: optimize_partition not defined

### ISSUE THREAD

**Issue by lazarusA** [afternone/CommunityDetection.jl#1]
I'm trying to use the function optimize_partition and the only thing that I get is the following:

================================================
[ ERROR: CommunityDetection ]================================================

failed process: Process(`/Applications/Julia-0.5.app/Contents/Resources/julia/bin/julia -Ccore2 -J/Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes /Users/lazaro/.julia/v0.5/CommunityDetection/test/runtests.jl`, ProcessExited(1)) [1]

=============================================================================================================================
ERROR: CommunityDetection had test errors
 in #test#61(::Bool, ::Function, ::Array{AbstractString,1}) at ./pkg/entry.jl:740
 in (::Base.Pkg.Entry.#kw##test)(::Array{Any,1}, ::Base.Pkg.Entry.#test, ::Array{AbstractString,1}) at ./<missing>:0
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}})() at ./pkg/dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}}, ::String) at ./file.jl:59
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at ./pkg/dir.jl:31
 in (::Base.Pkg.Dir.#kw##cd)(::Array{Any,1}, ::Base.Pkg.Dir.#cd, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at ./<missing>:0
 in #test#3(::Bool, ::Function, ::String, ::Vararg{String,N}) at ./pkg/pkg.jl:258
 in test(::String, ::Vararg{String,N}) at ./pkg/pkg.jl:258

Any help will be useful. Thanks!

**Comment by afternone** [comment]
I find the function `optimize_partition` in line 15 of `/test/runtest.jl` should be `optimize_partition!`, and the change has been made. Please `Pkg.update()` and try again!

**Comment by lazarusA** [comment]
Ok. Thanks! Another issue is that in  the USAGE section you must change how you call the function  
optimize_partition(mp) #  for optimize_partition!(mp) instead.

**Comment by afternone** [comment]
Thanks for your reminder. Any other problems please contact me.
