### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by anuraag94** [afternone/CommunityDetection.jl#2]
Is there full documentation I can access via `?CommunityDetection` or something in the repl? For my application, I'd like to calculate the Louvain modularity for a partition made on a weighted graph, and then while keeping the partition the same, the modularity for the unweighted version of the original weighted graph. I'm trying to figure out how to do this, any help would be appreciated!

Update: Trying to run the test code in the readme, and I'm unable. Do you know if this works with Julia 1.0?

**Comment by afternone** [comment]
The signature of the `modularity` function is
```julia
function modularity{V,T<:Real}(graph::AbstractGraph{V}, membership::Vector{Int}, weights::Vector{T})
```
So, you can calculate the modularity without considering weights as follows:
```julia
modularity(graph, membership, ones(num_edges(graph)))
```
This package should work fine at 0.6, and there have been many changes from 0.6 to 1.0, so there may be some problems with julia 1.0.

**Comment by anuraag94** [comment]
Hmm, it might be because of 1.0, it fails on precompile. Not very keen on downgrading the rest of my code to 0.6, but if I can use this the way I need to, I'll give it a shot.

To clarify, does the `modularity` function calculate the optimized modularity according to the two-phase Louvain method? What I'd like to do is get the Louvain-optimized modularity for the weighted graph, then, using the _same_ community structure that Louvain optimized for on the weighted graph, calculate the modularity on the unweighted graph. NB: this won't necessarily be the Louvain-optimized modularity on the unweighted graph. I'm not sure if this is possible with this package, but if you have any ideas I'd love to hear them.
